add model result and changes to User and Test
Melifaro8/test-guru pull request #4
Opened 2022-08-07 08:47 UTC by Melifaro8

2022-08-07 12:49 UTC, VidgarVii requested changes

2022-08-07 12:49 UTC, VidgarVii commented on app/models/test.rb
> +    Tset.joins(:test).where(categories: {title: category_title}).order(title: :desk).pluck(:title)
что тут происходит? Всегда тестируй код, который пишешь

2022-08-07 12:49 UTC, VidgarVii commented on app/models/user.rb
> +  end
так же метод не был протестирован. И нет понимания что тут вообще происходит =(

2022-08-07 12:49 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN results ON results.test_id = test.id').where(:level => level).where(results: {user_id => user.id})
(:level => level)
старый синтаксис.
(level: level)

2022-08-07 12:49 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create!([{body: 'answer 1', question_id: questions[0].id}, {body: 'answer 2', question_id: questions[1].id}, {body: 'answer 3', question_id: questions[2].id}, {body: 'answer 4', ques
переменная answers не используется. Нет смысла её создавать

2022-08-07 12:49 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create!([{body: 'answer 1', question_id: questions[0].id}, {body: 'answer 2', question_id: questions[1].id}, {body: 'answer 3', question_id: questions[2].id}, {body: 'answer 4', ques
в целом в этом файле всё хорошо. Но данных мало. Тяжело будет это тестировать

2022-08-07 12:49 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create!([{body: 'answer 1', question_id: questions[0].id}, {body: 'answer 2', question_id: questions[1].id}, {body: 'answer 3', question_id: questions[2].id}, {body: 'answer 4', ques
какой из ответов будет верный?

2022-08-09 13:11 UTC, Melifaro8 commented on db/seeds.rb
> +answers = Answer.create!([{body: 'answer 1', question_id: questions[0].id}, {body: 'answer 2', question_id: questions[1].id}, {body: 'answer 3', question_id: questions[2].id}, {body: 'answer 4', ques
вроде тот, что указан в question_id

2022-08-10 11:06 UTC, merged